### Prometheus Endpoint
GET https://localhost:5000/metrics
Accept: application/json

### Health Endpoint
GET https://localhost:5000/health
Accept: application/json

### Order Subscription
GRPC grpcs://localhost:5223/Agora.Simulator.Market/SubscribeToOrders

{
  "instrument": "ABC"
}
