apiVersion: v1
kind: Service
metadata:
  name: {{ include "agora-simulator.fullname" . }}
  labels:
    {{- include "agora-simulator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: UDP
      name: grpc
  selector:
    {{- include "agora-simulator.selectorLabels" . | nindent 4 }}
