services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_INSTALL_PLUGINS=heywesty-trafficlight-panel
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  agora-simulator:
    image: agora-simulator
    container_name: agora-simulator
    ports:
      - 5223:5223
      - 5000:5000
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS="https://+"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Agora.Simulator.pfx
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=/run/secrets/certificate_password
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=75g9Re7k6rMQ6laAyOol
    volumes:
      - ~/.aspnet/https:/https:ro
    secrets:
      - certificate_password

secrets:
  certificate_password:
    file: ./ASPNETCORE_Kestrel__Certificates__Default__Password

volumes:
  prom_data:
