<Project Sdk="Aspire.AppHost.Sdk/13.1.1">
  
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <UserSecretsId>bfc194bf-f8e1-4f35-9736-5f10866ee6f5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agora.PersistenceWorker\Agora.PersistenceWorker.csproj" />
    <ProjectReference Include="..\Agora.Simulator\Agora.Simulator.csproj" />
  </ItemGroup>

</Project>
